version: '3.6'
services:
  java:
    image: openjdk:17
    expose:
      - 8080
    network_mode: "host"
    tty: true
    volumes:
      - ./java:/srv:cached
    working_dir: /srv
  react:
    build: 
      context: ./react
      dockerfile: Dockerfile
    # ホスト側のディレクトリをコンテナ側のディレクトリにマウントする
    volumes:
      - ./react/src:/usr/src/app/
    expose:
      - 3000
    tty: true
    network_mode: "host"
  postgres:
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: $POSTGRESUSER
      POSTGRES_PASSWORD: $POSTGRESPASSWORD
      POSTGRES_DB: dev_db
    volumes:
      - expenditure_data:/var/lib/postgresql/data
    hostname: postgres
    network_mode: "host" 
volumes:
  expenditure_data:
    driver: local
